### PR TITLE
Added background

### PR DESCRIPTION
**Pull request by MiroTheSuperDev**
Test link requested by @HimbeersaftLP http://test.mcrafters.ml

### CODE REVIEW

**Comment by HimbeersaftLP** [comment]
Spacing?

**Comment by MiroTheSuperDev** [comment]
@HimbeersaftLP Please tell me more about what you mean .

Are you talking about why pictures are small and repeated ???

That's just because the size of the picture is small but if i stretched it 

It will look ugly

**Comment by HimbeersaftLP** [comment]
Code spacing

**Comment by MiroTheSuperDev** [comment]
I have looked in lots of professional​css templates and have found that all
of them do it like that.

For making their code easy to understand and learn from.

**Comment by HimbeersaftLP** [comment]
Shouldn't it look like this:
```
<style type="text/css">
body {
  some stuff here
}
</style>
```

**Comment by MiroTheSuperDev** [comment]
Text css in css sheets  or  text JavaScript classes isn't​ necessary in
most cases for me is as it still works without it many times.

You can edit the pull request and change it to your preference coding style.

**Comment by HimbeersaftLP** [comment]
Of course it works without, but it looks nice :P

**Pull request closed without merging**
